### ISSUE TITLE
Level 3 score calculation is wrong

### ISSUE THREAD

**Issue by IceflowRE** [Greaby/godot-qrcode-generator#10]
https://github.com/Greaby/godot-qrcode-generator/blob/main/classes/qr_code.gd#L559-L580

According to https://www.thonky.com/qr-code-tutorial/data-masking#evaluation-condition-3. The pattern you check for needs also 4 white modules on one side.

![](https://www.thonky.com/qr-code-tutorial/penalty-3-pattern1.png)

![](https://www.thonky.com/qr-code-tutorial/penalty-3-pattern2.png)

**Comment by Greaby** [comment]
Ok thanks for the report.
