### ISSUE TITLE
Issue with encoding larger amounts of data

### ISSUE THREAD

**Issue by Kontrano** [Greaby/godot-qrcode-generator#5]
Hi, Im not sure this is a bug or not but when trying to incode more than a set amount of data, the qr code seems to get corrupted as you can see in the image on the left side. 

Any idea's?
![image](https://user-images.githubusercontent.com/80490564/194961459-8007f7fc-5c1d-4bba-b5a8-4a0c456803a3.png)

**Comment by Greaby** [comment]
Yes, I forgot to implement that from a certain amount of data, the code must be separated into chunks.

**Comment by Kontrano** [comment]
Ah ok, I've temporarily found a different way to generate QR codes via an Online API for my purpose but having it via Godot Internal would be much better.

**Comment by Greaby** [comment]
I fixed it, it should now work with large amounts of data.

**Comment by Kontrano** [comment]
Nice thanks a lot for implementing it :)
