### ISSUE TITLE
Gray pixels in QR texture

### ISSUE THREAD

**Issue by PolRecasensSarra** [Greaby/godot-qrcode-generator#9]
There are few gray pixels in the QR texture, meaning that the generated array of bools has Null entries. I don't know if this can cause problems when reading the QR, missing some characters in a long string.

![Screenshot from 2022-11-14 11-02-50](https://user-images.githubusercontent.com/36154612/201632043-9352417c-6bec-49c7-ab06-1d7a59b27072.png)

**Comment by Greaby** [comment]
Hello, thanks for reporting the issue!
The QR code seems to work fine.
But perhaps it's because of the error correction and the end of the code is corrupted.
I'll check that.

**Comment by IceflowRE** [comment]
The Reed Solomon file seems to be correct tho.

**Comment by IceflowRE** [comment]
Did you probably missed the remainder bits after the structured message?

On first look i didn't find them.

---

[Reference](https://www.thonky.com/qr-code-tutorial/structure-final-message#step-4-add-remainder-bits-if-necessary)

**Comment by Greaby** [comment]
Thanks @IceflowRE !
It was that. I forgot to add the remainder bits at the end.
